#!/bin/sh
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007-2022  IPFire Team  <info@ipfire.org>                     #
# Copyright (C) 2024  FireBeeOS <vincent.mc.li@gmail.com>                     #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

. /etc/sysconfig/rc
. $rc_functions

eval $(/usr/local/bin/readhash /var/ipfire/ddos/settings)

get_ports () {
# Define an empty variable to store the output
	local output=""

# Read the input file line by line
	while IFS= read -r line; do
		# Check if the line contains '=on'
		if [[ "$line" == [0-9]*"=on" ]]; then
			# Extract the service/port number
			service=$(echo "$line" | cut -d'=' -f1)
			# Append the service/port number to the output string
			output="$output$service,"
		fi
	done < /var/ipfire/ddos/settings

	# Remove the trailing comma from the output string
	output="${output%,}"
	echo $output
}

ports="$(get_ports)"

case "$1" in
	start)
		boot_mesg -n "Starting ddos..."
		if [ -e /var/ipfire/red/active ]; then
			boot_mesg ""
			sysctl -w net.ipv4.tcp_syncookies=2
			sysctl -w net.ipv4.tcp_timestamps=1
			sysctl -w net.netfilter.nf_conntrack_tcp_loose=0
			/usr/sbin/xdp-loader status red0 | grep 'syncookie_xdp'
			if [ $? -eq 0 ]; then
				prog_id=$(xdp-loader status red0 | grep 'syncookie_xdp' | awk '{print $4}')
				xdp_synproxy --prog $prog_id --ports="$ports"
			else
				xdp-loader load red0 -m skb /usr/lib/bpf/xdp_synproxy.bpf.o
				evaluate_retval
				prog_id=$(/usr/sbin/xdp-loader status red0 | grep 'syncookie_xdp' | awk '{print $4}')
				xdp_synproxy --prog $prog_id --ports="$ports"
			fi
		else
			boot_mesg " ERROR! Red0 interface not online!"
			echo_warning
		fi

		;;

	stop)
		boot_mesg "Stopping ddos..."
		sysctl -w net.ipv4.tcp_syncookies=1
		/usr/sbin/xdp-loader unload red0 -a
		evaluate_retval
		/bin/rm -rf /sys/fs/bpf/*
		evaluate_retval
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		/usr/sbin/xdp-loader status red0
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac
